# Generated by Django 2.1.8 on 2019-06-20 13:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('coursefinder', '0006_coursefinderpostcode_coursefindertowncity_coursefinderuni'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFinderResults',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.TextField(blank=True)),
                ('related_links_title', models.TextField(blank=True)),
                ('related_links', wagtail.core.fields.StreamField([('links', wagtail.core.blocks.PageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
