# Generated by Django 2.1.8 on 2019-06-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursefinder', '0007_coursefinderresults'),
        ('coursefinder', '0009_coursefindersummary'),
    ]

    operations = [
    ]
