# Generated by Django 2.2.3 on 2019-08-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('coursefinder', '0010_merge_20190621_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseFinderLandingPage',
        ),
    ]
