# Generated by Django 2.2.3 on 2019-08-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('coursefinder', '0012_auto_20190812_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefinderchoosecountry',
            name='next_section',
        ),
    ]
