# Generated by Django 2.2.3 on 2019-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('coursefinder', '0013_auto_20190812_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefinderchoosecountry',
            name='helper_text',
        ),
    ]
