# Generated by Django 4.0.10 on 2025-10-21 16:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coursefinder', '0016_auto_20190910_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefinderresults',
            name='related_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock())], use_json_field=True),
        ),
    ]
