# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
trigger:
- develop

pr: none

pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'discover-uni:$(Build.BuildId)'

steps:
- template: .azuredevops/azure-template.yml
  parameters:
    dockerId: 'preproddiscoverunicontainerregistry'
