# Generated by Django 2.2.3 on 2019-08-08 16:35

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_items', wagtail.core.fields.StreamField([('simple_menu_item', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('multi_menu_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(required=False)), ('menu_items', wagtail.core.blocks.StreamBlock([('simple_menu_item', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))]))], icon='arrow-left', label='Items'))]))])),
            ],
        ),
    ]
