# Generated by Django 2.2.4 on 2019-09-08 07:12

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190808_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('footer_items', wagtail.core.fields.StreamField([('footer_item', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))]))])),
            ],
        ),
    ]
