# Generated by Django 4.0.10 on 2025-10-21 16:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220630_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_items',
            field=wagtail.fields.StreamField([('footer_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(required=False))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.fields.StreamField([('simple_menu_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(required=False))])), ('multi_menu_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(required=True)), ('menu_items', wagtail.blocks.StreamBlock([('simple_menu_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(help_text='Leave blank to use the page name', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(required=False))]))], icon='arrow-left', label='Items'))]))], use_json_field=True),
        ),
    ]
