"""
Django settings for CMS project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from corsheaders.defaults import default_headers

from . import constants as sys_constants

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

DEBUG = True  # sys_constants.OFS_CONF_DEBUG
LOCAL = sys_constants.OFS_CONF_LOCAL
READ_ONLY = sys_constants.OFS_CONF_READ_ONLY
ALLOWED_HOSTS = sys_constants.OFS_CONF_ALLOWED_HOSTS
SECRET_KEY = sys_constants.OFS_CONF_SECRET_KEY
print(f"\t\t \nallowed hosts\n\t\t {ALLOWED_HOSTS[1]}")
ROOT_DOMAIN = sys_constants.OFS_CONF_ROOT_DOMAIN

SECURE_HSTS_SECONDS = sys_constants.OFS_CONF_SECURE_HSTS_SECONDS
SECURE_HSTS_INCLUDE_SUBDOMAINS = sys_constants.OFS_CONF_SECURE_HSTS_INCLUDE_SUBDOMAINS
SECURE_HSTS_PRELOAD = sys_constants.OFS_CONF_SECURE_HSTS_PRELOAD
SECURE_CONTENT_TYPE_NOSNIFF = sys_constants.OFS_CONF_SECURE_CONTENT_TYPE_NOSNIFF
SECURE_BROWSER_XSS_FILTER = sys_constants.OFS_CONF_SECURE_BROWSER_XSS_FILTER
SESSION_COOKIE_SECURE = sys_constants.OFS_CONF_SESSION_COOKIE_SECURE
CSRF_COOKIE_SECURE = sys_constants.OFS_CONF_CSRF_COOKIE_SECURE

# Application definition

INSTALLED_APPS = [
    'customadmin',
    'django.contrib.sitemaps',
    'wagtail.contrib.forms',
    'wagtail.contrib.modeladmin',
    'wagtail.contrib.redirects',
    # 'wagtail.contrib.frontend_cache',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',
    'corsheaders',
    'axes',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'core.apps.CoreConfig',
    'content.apps.ContentConfig',
    'coursefinder.apps.CoursefinderConfig',
    'courses.apps.CoursesConfig',
    'errors.apps.ErrorsConfig',
    'home.apps.HomeConfig',
    'institutions.apps.InstitutionsConfig',
    'search.apps.SearchConfig',
    'site_search.apps.SiteSearchConfig',
    'widget.apps.WidgetConfig',

    'sass_processor',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # AxesMiddleware should be the last middleware in the MIDDLEWARE list.
    # It only formats user lockout messages and renders Axes lockout responses
    # on failed user authentication attempts from login views.
    # If you do not want Axes to override the authentication response
    # you can skip installing the middleware and use your own views.
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'CMS.urls'
print(PROJECT_DIR)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'CMS.context_processors.nav_menu_render'
            ],
        },
    },
]

WSGI_APPLICATION = 'CMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': sys_constants.OFS_CONF_DBNAME,
            'HOST': sys_constants.OFS_CONF_DBHOST,
            'USER': sys_constants.OFS_CONF_DBUSER,
            'PORT': sys_constants.OFS_CONF_DBPORT,
            'PASSWORD': sys_constants.OFS_CONF_DBPASSWORD
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# Javascript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

SASS_PROCESSOR_ROOT = os.path.join(PROJECT_DIR, 'static/css')

SASS_PROCESSOR_INCLUDE_FILE_PATTERN = r'^.+\.scss$'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'sass_processor.finders.CssFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
]

# Wagtail settings

WAGTAIL_SITE_NAME = "CMS"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = sys_constants.OFS_CONF_ROOT_DOMAIN

# Search API settings

SORT_BY_SUBJECT_LIMIT = sys_constants.OFS_CONF_SORT_BY_SUBJECT_LIMIT
SEARCHAPIHOST = sys_constants.OFS_CONF_SEARCHAPIHOST
DATASETAPIHOST = sys_constants.OFS_CONF_DATASETAPIHOST
DATASETAPIKEY = sys_constants.OFS_CONF_DATASETAPIKEY
AZURECOSMOSDBURI = sys_constants.OFS_CONF_AZURECOSMOSDBURI
AZURECOSMOSDBKEY = sys_constants.OFS_CONF_AZURECOSMOSDBKEY
# MONGODB_HOST = sys_constants.OFS_CONF_MONGODB_HOST
# MONGODB_USERNAME = sys_constants.OFS_CONF_MONGODB_USERNAME
# MONGODB_PASSWORD = sys_constants.OFS_CONF_MONGODB_PASSWORD
# TEST_COURSES = sys_constants.OFS_CONF_TEST_COURSES
WIDGETAPIKEY = sys_constants.OFS_CONF_WIDGETAPIKEY
WIDGETAPIHOST = sys_constants.OFS_CONF_WIDGETAPIHOST
FEEDBACK_API_HOST = sys_constants.OFS_CONF_FEEDBACK_API_HOST
JSONFILES_STORAGE_CONTAINER = sys_constants.OFS_CONF_JSONFILES_STORAGE_CONTAINER
SITEMAP_STORAGE_BLOB = sys_constants.OFS_CONF_SITEMAP_STORAGE_BLOB
STORAGEKEY = sys_constants.OFS_CONF_STORAGEKEY
STORAGE_ACCOUNT_NAME = sys_constants.OFS_CONF_STORAGE_ACCOUNT_NAME

DEFAULT_FILE_STORAGE = sys_constants.OFS_CONF_DEFAULT_FILE_STORAGE
AZURE_ACCOUNT_NAME = sys_constants.OFS_CONF_AZURE_ACCOUNT_NAME  # eg. 'campaignstorage'
AZURE_ACCOUNT_KEY = sys_constants.OFS_CONF_AZURE_ACCOUNT_KEY  # eg. '<secret key>'
AZURE_CONTAINER = sys_constants.OFS_CONF_AZURE_CONTAINER  # eg. 'campaign-resource-centre'

SENDGRID_API_KEY = sys_constants.OFS_CONF_SENDGRID_API_KEY
EMAIL_BACKEND = sys_constants.OFS_CONF_EMAIL_BACKEND
EMAIL_HOST = sys_constants.OFS_CONF_EMAIL_HOST
EMAIL_HOST_USER = sys_constants.OFS_CONF_EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = sys_constants.OFS_CONF_EMAIL_HOST_PASSWORD
EMAIL_PORT = sys_constants.OFS_CONF_EMAIL_PORT
EMAIL_USE_TLS = sys_constants.OFS_CONF_EMAIL_USE_TLS

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'ocp-apim-subscription-key',
]

X_FRAME_OPTIONS = 'DENY'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# Django Axes settings
AXES_CACHE = 'axes_cache'
AXES_LOGIN_FAILURE_LIMIT = 5
AXES_LOCK_OUT_AT_FAILURE = True
AXES_COOLOFF_TIME = 1  # Locks user out for 1 hour
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
# If True, prevent login from IP under a particular username if the attempt limit has been exceeded,
# otherwise lock out based on IP.

# Anti  Virus
CLAMAV_ACTIVE = True

WAGTAILEMBEDS_FINDERS = [
    {
        'class': 'wagtail.embeds.finders.oembed',
        'providers': [
            {
                "endpoint": "https://www.youtube.com/oembed",
                "urls": [
                    r'^https?://(?:[-\w]+\.)?youtube\.com/watch.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/v/.+$',
                    r'^https?://youtu\.be/.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/user/.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/[^#?/]+#[^#?/]+/.+$',
                    r'^https?://m\.youtube\.com/index.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/profile.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/view_play_list.+$',
                    r'^https?://(?:[-\w]+\.)?youtube\.com/playlist.+$',
                ],
            }
        ],
        'options': {'scheme': 'https'}
    },
    {
        'class': 'wagtail.embeds.finders.oembed',
    }
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
