from decouple import config

OFS_CONF_SECRET_KEY = config('SECRET_KEY')
OFS_CONF_DEBUG = "True"
OFS_CONF_LOCAL = config('LOCAL', default=True, cast=bool)
OFS_CONF_READ_ONLY = config('READ_ONLY', default=False, cast=bool)
OFS_CONF_ROOT_DOMAIN = config('ROOT_DOMAIN', default='http://localhost:3000')
OFS_CONF_DBNAME = config('DBNAME')
OFS_CONF_DBHOST = config('DBHOST')
OFS_CONF_DBUSER = config('DBUSER')
OFS_CONF_DBPORT = config('DBPORT')
OFS_CONF_DBPASSWORD = config('DBPASSWORD')
OFS_CONF_ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])
OFS_CONF_CORS_ORIGIN_ALLOW_ALL = config("CORS_ORIGIN_ALLOW_ALL", cast=bool, default=False)
OFS_CONF_BASE_URL = config('ROOT_DOMAIN', default='http://example.com')

# Search API settings
OFS_CONF_SORT_BY_SUBJECT_LIMIT = config('SORT_BY_SUBJECT_LIMIT', cast=int)
OFS_CONF_SEARCHAPIHOST = config('SEARCHAPIHOST')
OFS_CONF_DATASETAPIHOST = config('DATASETAPIHOST')
OFS_CONF_DATASETAPIKEY = config('DATASETAPIKEY')
OFS_CONF_AZURECOSMOSDBURI = config('AZURECOSMOSDBURI')
OFS_CONF_AZURECOSMOSDBKEY = config('AZURECOSMOSDBKEY')
OFS_CONF_WIDGETAPIKEY = config('WIDGETAPIKEY')
OFS_CONF_WIDGETAPIHOST = config('WIDGETAPIHOST')
OFS_CONF_FEEDBACK_API_HOST = config('FEEDBACK_API_HOST')
OFS_CONF_JSONFILES_STORAGE_CONTAINER = config('JSONFILES_STORAGE_CONTAINER', "")
OFS_CONF_SITEMAP_STORAGE_BLOB = config('SITEMAP_STORAGE_BLOB', "")
OFS_CONF_STORAGEKEY = config('STORAGEKEY')
OFS_CONF_STORAGE_ACCOUNT_NAME = config('STORAGE_ACCOUNT_NAME')
OFS_CONF_DEFAULT_FILE_STORAGE = config('DEFAULT_FILE_STORAGE', default='django.core.files.storage.FileSystemStorage')
OFS_CONF_AZURE_ACCOUNT_NAME = config('AZURE_ACCOUNT_NAME')  # eg. 'campaignstorage'
OFS_CONF_AZURE_ACCOUNT_KEY = config('AZURE_ACCOUNT_KEY')  # eg. '<secret key>'
OFS_CONF_AZURE_CONTAINER = config('AZURE_CONTAINER')  # eg. 'campaign-resource-centre'

OFS_CONF_SENDGRID_API_KEY = config('SENDGRID_API_KEY', default=None)
OFS_CONF_EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
OFS_CONF_EMAIL_HOST = config('EMAIL_HOST', default=None)
OFS_CONF_EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=None)
OFS_CONF_EMAIL_HOST_PASSWORD = OFS_CONF_SENDGRID_API_KEY
OFS_CONF_EMAIL_PORT = config('EMAIL_PORT', default=None)
OFS_CONF_EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=None)

OFS_CONF_SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', 0)
OFS_CONF_SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool, default=False)
OFS_CONF_SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool, default=False)
OFS_CONF_SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', cast=bool, default=False)
OFS_CONF_SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', cast=bool, default=False)
OFS_CONF_SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool, default=False)
OFS_CONF_CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool, default=False)
