# Generated by Django 2.2.3 on 2019-07-12 07:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='accordions',
            field=wagtail.fields.StreamField([('accordion_panel', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('data_set', wagtail.blocks.ChoiceBlock(choices=[('student_satisfaction', 'Student Satisfaction')]))], icon='collapse-down', required=True))], default=[]),
            preserve_default=False,
        ),
    ]
