# Generated by Django 2.2.3 on 2019-07-12 08:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursedetailpage_accordions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='accordions',
            field=wagtail.core.fields.StreamField([('accordion_panel', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('data_set', wagtail.core.blocks.ChoiceBlock(choices=[('student_satisfaction', 'Student satisfaction'), ('entry_information', 'Entry information'), ('after_one_year', 'After 1 year of study'), ('after_the_course', 'After the course'), ('professional_accreditation', 'Professional accreditation')]))], icon='collapse-down', required=True))]),
        ),
    ]
