# Generated by Django 2.2.4 on 2019-09-06 10:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('courses', '0011_coursecomparisonpage_accordions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseManagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.TextField(blank=True)),
                ('lead', models.TextField(blank=True)),
                ('save_text', wagtail.core.fields.RichTextField(blank=True)),
                ('compare_text', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
