# Generated by Django 2.2.4 on 2019-09-06 15:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursemanagepage_none_selected_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemanagepage',
            name='one_selected_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
