# Generated by Django 2.1.8 on 2019-04-24 13:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190424_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='info_headline',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_points',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
