# Generated by Django 2.1.8 on 2019-04-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190424_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='find_text',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='find_title',
            new_name='left_CTA',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='header_subtitle',
            new_name='right_CTA',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='help_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='info_headline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='info_points',
        ),
    ]
