# Generated by Django 2.1.8 on 2019-06-04 11:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190430_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='left_CTA',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='right_CTA',
        ),
        migrations.AddField(
            model_name='homepage',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.PageChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
