# Generated by Django 2.1.8 on 2019-06-04 11:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
