# Generated by Django 2.1.8 on 2019-06-04 11:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.PageChooserBlock()), ('link_header', wagtail.blocks.TextBlock())]),
        ),
    ]
