# Generated by Django 2.1.8 on 2019-06-04 12:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190604_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.RichTextBlock())]),
        ),
    ]
