# Generated by Django 2.1.8 on 2019-06-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190604_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='links',
        ),
    ]
