# Generated by Django 2.1.8 on 2019-06-04 12:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_homepage_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.CharBlock())]))], default=''),
            preserve_default=False,
        ),
    ]
