# Generated by Django 2.1.8 on 2019-06-12 09:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_page_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('title', wagtail.blocks.CharBlock())]))]),
        ),
    ]
