# Generated by Django 2.1.8 on 2019-06-12 14:37

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190612_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='course_field_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='institution_field_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_header',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
