# Generated by Django 2.2.3 on 2019-08-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190805_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='course_field_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='institution_field_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_header',
        ),
    ]
