# Generated by Django 2.2.3 on 2019-08-07 08:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0018_auto_20190805_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNavPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', models.TextField()),
                ('nav_panels', wagtail.core.fields.StreamField([('satisfaction_panel', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('magnify_glass', 'Magnify glass'), ('info', "Info 'i'"), ('institution', 'Institution'), ('payment', 'Payment'), ('clipboard', 'Clipboard')], classname='dct-meta-field', label='Variant')), ('label', wagtail.core.blocks.RichTextBlock()), ('button_text', wagtail.core.blocks.CharBlock())], icon='link', required=True))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
