# Generated by Django 2.2.3 on 2019-08-07 08:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_usernavpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernavpage',
            name='nav_panels',
            field=wagtail.fields.StreamField([('nav_panel', wagtail.blocks.StructBlock([('icon', wagtail.blocks.ChoiceBlock(choices=[('magnify_glass', 'Magnify glass'), ('info', "Info 'i'"), ('institution', 'Institution'), ('payment', 'Payment'), ('clipboard', 'Clipboard')], classname='dct-meta-field', label='Variant')), ('label', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock(required=False))], icon='link', required=True))]),
        ),
    ]
