# Generated by Django 2.2.4 on 2019-09-10 21:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190910_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernavpage',
            name='nav_panels',
            field=wagtail.core.fields.StreamField([('nav_panel', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock()), ('icon', wagtail.core.blocks.ChoiceBlock(choices=[('magnify_glass', 'Magnify glass'), ('info', "Info 'i'"), ('institution', 'Institution'), ('payment', 'Payment'), ('clipboard', 'Clipboard')], classname='dct-meta-field', label='Variant')), ('label', wagtail.core.blocks.RichTextBlock()), ('button_text', wagtail.core.blocks.CharBlock(required=False)), ('button_description', wagtail.core.blocks.CharBlock(required=False))], icon='link', required=True))]),
        ),
    ]
