# Generated by Django 2.2.13 on 2020-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190910_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='box_1_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_1_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_1_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_2_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_2_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_2_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_3_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='course_wizard_link',
            field=models.TextField(blank=True),
        ),
    ]
