# Generated by Django 2.2.13 on 2022-03-29 13:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0024_auto_20200818_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='informational_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='informational_text_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='informational_title',
            field=models.TextField(blank=True),
        ),
    ]
