# Generated by Django 2.2.13 on 2022-03-03 09:12

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200818_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='informational_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='informational_text_link',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='informational_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
