# Generated by Django 3.2.14 on 2025-01-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220329_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='box_3_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='box_3_title',
            field=models.TextField(blank=True),
        ),
    ]
