# Generated by Django 2.2.13 on 2022-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220303_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='informational_text_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='informational_title',
            field=models.TextField(blank=True),
        ),
    ]
