# Generated by Django 4.0.10 on 2025-10-21 16:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20250127_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock()), ('title', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='usernavpage',
            name='nav_panels',
            field=wagtail.fields.StreamField([('nav_panel', wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock()), ('icon', wagtail.blocks.ChoiceBlock(choices=[('magnify_glass', 'Magnify glass'), ('info', "Info 'i'"), ('institution', 'Institution'), ('payment', 'Payment'), ('clipboard', 'Clipboard')], classname='dct-meta-field', label='Variant')), ('label', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock(required=False)), ('button_description', wagtail.blocks.CharBlock(required=False))], icon='link', required=True))], use_json_field=True),
        ),
    ]
