# Generated by Django 2.2.13 on 2022-04-05 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0025_auto_20220329_1315'),
        ('home', '0027_auto_20220303_1141'),
    ]

    operations = [
    ]
