# Generated by Django 2.1.8 on 2019-04-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheretostudy',
            old_name='body',
            new_name='options',
        ),
    ]
