# Generated by Django 2.1.8 on 2019-04-30 15:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0003_searchtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheretostudy',
            name='options',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.TextBlock())]),
        ),
    ]
