# Generated by Django 2.1.8 on 2019-05-01 10:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('searchtool', '0004_auto_20190430_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseAUni',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', wagtail.core.fields.RichTextField(blank=True)),
                ('placeholder', models.TextField(blank=True)),
                ('button', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
