# Generated by Django 2.1.8 on 2019-05-01 12:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('searchtool', '0006_whattostudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToStudy',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', wagtail.core.fields.RichTextField(blank=True)),
                ('options', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.TextBlock(blank=True))])),
                ('button', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
