# Generated by Django 2.1.8 on 2019-05-02 10:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('searchtool', '0007_howtostudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseALocation',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header', wagtail.core.fields.RichTextField(blank=True)),
                ('tab_headings', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.TextBlock())])),
                ('country_options', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.TextBlock(blank=True))])),
                ('tab_two_header', wagtail.core.fields.RichTextField(blank=True)),
                ('tab_two_placeholder', models.TextField(blank=True)),
                ('tab_three_header', wagtail.core.fields.RichTextField(blank=True)),
                ('tab_three_placeholder', models.TextField(blank=True)),
                ('button', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
