# Generated by Django 2.1.8 on 2019-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0008_choosealocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosealocation',
            name='help_decide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='howtostudy',
            name='help_decide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whattostudy',
            name='help_decide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wheretostudy',
            name='help_decide',
            field=models.TextField(blank=True),
        ),
    ]
