# Generated by Django 2.1.8 on 2019-05-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlandingpage',
            name='header',
        ),
    ]
