# Generated by Django 2.1.8 on 2019-05-30 13:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.core.fields.StreamField([('subsection_title', wagtail.core.blocks.CharBlock(classname='full title')), ('content', wagtail.core.blocks.RichTextBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())]),
        ),
    ]
