# Generated by Django 2.1.8 on 2019-05-30 13:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20190530_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.RichTextBlock())]),
        ),
    ]
