# Generated by Django 2.1.8 on 2019-06-03 07:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20190530_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed']))]),
        ),
    ]
