# Generated by Django 2.1.8 on 2019-06-03 18:12

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20190603_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='lateral_link_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='lateral_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.PageChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
