# Generated by Django 2.1.8 on 2019-06-04 09:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20190603_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlandingpage',
            name='options',
            field=wagtail.core.fields.StreamField([('sections', wagtail.core.blocks.PageChooserBlock())]),
        ),
    ]
