# Generated by Django 2.1.8 on 2019-06-26 08:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20190604_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.StructBlock([('subsection_title', wagtail.blocks.TextBlock()), ('subsection_content', wagtail.blocks.RichTextBlock())]))]),
        ),
    ]
