# Generated by Django 2.1.8 on 2019-06-26 10:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20190626_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='related_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock())], blank=True),
        ),
    ]
