# Generated by Django 2.1.8 on 2019-06-26 11:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20190626_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='lateral_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock(required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='related_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock(required=False))], blank=True),
        ),
    ]
