# Generated by Django 2.2.3 on 2019-08-07 13:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20190626_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlandingpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
