# Generated by Django 2.2.3 on 2019-08-18 21:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_contentlandingpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
