# Generated by Django 2.2.4 on 2019-09-10 19:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('content', '0016_flatcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlandingpage',
            name='translated_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='flatcontent',
            name='translated_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='section',
            name='translated_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.StructBlock([('subsection_title', wagtail.blocks.TextBlock()), ('subsection_content', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'embed', 'link', 'document-link', 'image', 'ol', 'ul', 'hr', 'blockquote']))]))]),
        ),
    ]
