# Generated by Django 2.2.6 on 2019-10-09 11:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20190910_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.StructBlock([('subsection_title', wagtail.blocks.TextBlock()), ('subsection_content', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'embed', 'link', 'image', 'ol', 'ul', 'hr', 'blockquote']))]))]),
        ),
    ]
