# Generated by Django 4.0.10 on 2025-10-21 16:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_section_subsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlandingpage',
            name='options',
            field=wagtail.fields.StreamField([('sections', wagtail.blocks.PageChooserBlock())], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='lateral_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock(required=False))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='related_links',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.PageChooserBlock(required=False))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', wagtail.blocks.StructBlock([('subsection_title', wagtail.blocks.TextBlock()), ('subsection_content', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'underline', 'italic', 'embed', 'link', 'image', 'ol', 'ul', 'hr', 'blockquote']))]))], use_json_field=True),
        ),
    ]
