# Generated by Django 5.2.8 on 2025-11-11 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_contentlandingpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subsections',
            field=wagtail.fields.StreamField([('subsection', 2)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'underline', 'italic', 'embed', 'link', 'document-link', 'image', 'ol', 'ul', 'hr', 'blockquote']}), 2: ('wagtail.blocks.StructBlock', [[('subsection_title', 0), ('subsection_content', 1)]], {})}),
        ),
    ]
