# Generated by Django 2.2.3 on 2019-07-23 11:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('qa_heading', models.TextField(blank=True)),
                ('qa_body', wagtail.core.fields.RichTextField(blank=True)),
                ('qa_report_link', models.TextField(blank=True)),
                ('qa_explanation_link', models.TextField(blank=True)),
                ('qa_explanation_heading', models.TextField(blank=True)),
                ('qa_explanation_body', wagtail.core.fields.RichTextField(blank=True)),
                ('tef_heading', models.TextField(blank=True)),
                ('tef_report_link', models.TextField(blank=True)),
                ('tef_explanation_link', models.TextField(blank=True)),
                ('tef_explanation_heading', models.TextField(blank=True)),
                ('tef_explanation_body', wagtail.core.fields.RichTextField(blank=True)),
                ('apr_heading', models.TextField(blank=True)),
                ('apr_body', wagtail.core.fields.RichTextField(blank=True)),
                ('apr_explanation_link', models.TextField(blank=True)),
                ('apr_explanation_heading', models.TextField(blank=True)),
                ('apr_explanation_body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
