# Generated by Django 2.2.4 on 2019-08-21 15:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutiondetailpage',
            old_name='apr_body',
            new_name='apr_met_body',
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='apr_action_plan_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='apr_not_met_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='apr_pending_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
