# Generated by Django 2.2.4 on 2019-08-21 16:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20190821_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_bronze_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_gold_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_not_participated_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_provisional_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_silver_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutiondetailpage',
            name='tef_withdrawn_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
